/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: PersonFeatureMapper.java
 * Creat Date: 2015-08-15 11:30:16
 */
package com.cloudwalk.ibis.repository.featurelib;

import java.util.List;
import java.util.Map;

import org.springframework.dao.DataAccessException;

import com.cloudwalk.ibis.model.featurelib.PersonImportFlow;
import com.google.code.ssm.api.ReadThroughMultiCache;

public interface PersonImportFlowMapper {

	/**
	 * 分页查询导入记录信息
	 * @param map
	 * @return
	 * @throws DataAccessException
	 */
    @ReadThroughMultiCache(namespace ="PersonImportFlow", expiration = 30)
    List<PersonImportFlow> selectAllByPage(Map<String, Object> map) throws DataAccessException;
    
    /**
     * 根据导入记录信息查询满足条件的导入记录信息列表
     * @param record
     * @return
     * @throws DataAccessException
     */
    @ReadThroughMultiCache(namespace = "PersonImportFlow", expiration = 30)
	List<PersonImportFlow> searchAll(PersonImportFlow record) throws DataAccessException;
    
    /**
	 * 新增客户导入记录信息
	 * @param record
	 * @return
	 */
	int insertSelective(PersonImportFlow record);
	
	/**
	 * 修改客户导入记录信息
	 * @param record
	 * @return
	 */
	int updateByPrimaryKeySelective(PersonImportFlow record);
}