/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: PersonFeatureMapper.java
 * Creat Date: 2015-08-15 11:30:16
 */
package com.cloudwalk.ibis.repository.featurelib;

import java.util.List;
import java.util.Map;

import org.springframework.dao.DataAccessException;

import com.cloudwalk.ibis.model.featurelib.PersonFeature;
import com.google.code.ssm.api.ReadThroughMultiCache;

public interface PersonFeatureMapper {

	/**
	 * 分页查询特征信息
	 * @param map
	 * @return
	 * @throws DataAccessException
	 */
    @ReadThroughMultiCache(namespace ="PersonFeature", expiration = 30)
    List<PersonFeature> selectAllByPage(Map<String, Object> map) throws DataAccessException;
    
    /**
     * 根据特征信息查询满足条件的特征信息列表
     * @param record
     * @return
     * @throws DataAccessException
     */
    @ReadThroughMultiCache(namespace = "PersonFeature", expiration = 30)
	List<PersonFeature> searchAll(PersonFeature record) throws DataAccessException;
    
    /**
     * 查询客户特征信息
     * @param record
     * @return
     * @throws DataAccessException
     */
    @ReadThroughMultiCache(namespace = "PersonFeature", expiration = 30)
	List<PersonFeature> selectPersonFeature(PersonFeature record) throws DataAccessException;
    
    /**
     * 根据特征信息查询满足条件的特征信息列表
     * @param record
     * @return
     * @throws DataAccessException
     */
    @ReadThroughMultiCache(namespace = "PersonFeature", expiration = 30)
	List<PersonFeature> searchAllByPrimaryKey(PersonFeature record) throws DataAccessException;
    
    /**
	 * 新增客户特征信息
	 * @param record
	 * @return
	 */
	int insertSelective(PersonFeature record);
	
	/**
	 * 修改客户特征信息
	 * @param record
	 * @return
	 */
	int updateByPrimaryKeySelective(PersonFeature record);
	
	/**
	 * 根据personId以及引擎类型版本删除特征信息
	 * @param record
	 * @return
	 */
	int deleteByPersonIdAndEngine(PersonFeature record);
	
	/**
	 * 根据featureId查询filePath
	 * @param record
	 * @return
	 */
	String selectPathByFeatureId(PersonFeature record);
}