/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: Area.java
 * Creat Date: 2015-08-15 11:30:16
 */
package com.cloudwalk.ibis.model.system;

import java.io.Serializable;

import com.cloudwalk.common.util.ObjectUtils;

/**
 * Class Name: Area<br/>
 * Description: This class corresponds to the table - FND_AREA<br>
 * Create Date: 2015-08-15 11:30:16 <br/>
 */
public class Area implements Serializable {
    /**
	 * serialVersionUID:序列化ID,缓存需要  
	 */
    private static final long serialVersionUID = 1352825427306926477L;
    
    public Area() {
    	String uuid = ObjectUtils.createUUID();
    	this.areaId = uuid;
    }

    /**
     * FND_AREA.AREA_ID
     * 区域代码
     */
    private String areaId;

    /**
     * FND_AREA.AREA_NAME
     * 区域名称
     */
    private String areaName;

    /**
     * FND_AREA.PARENT_ID
     * 上级代码
     */
    private String parentId;

    /**
     * FND_AREA.AREA_LEVEL
     * 区域级别（1：省，2：市，3：县、市）
     */
    private Integer areaLevel;

    /**
     * This method returns the value of the database column
	 *	FND_AREA.AREA_ID (区域代码)
     * @return the value of FND_AREA.AREA_ID
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method sets the value of the database column
	 *	FND_AREA.AREA_ID (区域代码)
     * @param areaId the value for FND_AREA.AREA_ID
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId;
    }

    /**
     * This method returns the value of the database column
	 *	FND_AREA.AREA_NAME (区域名称)
     * @return the value of FND_AREA.AREA_NAME
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method sets the value of the database column
	 *	FND_AREA.AREA_NAME (区域名称)
     * @param areaName the value for FND_AREA.AREA_NAME
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method returns the value of the database column
	 *	FND_AREA.PARENT_ID (上级代码)
     * @return the value of FND_AREA.PARENT_ID
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method sets the value of the database column
	 *	FND_AREA.PARENT_ID (上级代码)
     * @param parentId the value for FND_AREA.PARENT_ID
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method returns the value of the database column
	 *	FND_AREA.AREA_LEVEL (区域级别（1：省，2：市，3：县、市）)
     * @return the value of FND_AREA.AREA_LEVEL
     */
    public Integer getAreaLevel() {
        return areaLevel;
    }

    /**
     * This method sets the value of the database column
	 *	FND_AREA.AREA_LEVEL (区域级别（1：省，2：市，3：县、市）)
     * @param areaLevel the value for FND_AREA.AREA_LEVEL
     */
    public void setAreaLevel(Integer areaLevel) {
        this.areaLevel = areaLevel;
    }
}