/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: Department.java
 * Creat Date: 2015-08-19 15:56:28
 */
package com.cloudwalk.ibis.model.system;

import java.io.Serializable;

/**
 * Class Name: Department<br/>
 * Description: This class corresponds to the table - FND_DEPARTMENT<br>
 * Create Date: 2015-08-19 15:56:28 <br/>
 */
public class Department implements Serializable {
   
	/**
	 * serialVersionUID:序列化ID,缓存需要  
	 */
    private static final long serialVersionUID = 2949312257720615953L; 
   

    /**
     * FND_DEPARTMENT.DEPT_CODE
     * 部门代码
     */
    private String deptCode;

    /**
     * FND_DEPARTMENT.ORG_CODE
     * 机构代码
     */
    private String orgCode;

    /**
     * FND_DEPARTMENT.DEPT_NAME
     * 部门名称
     */
    private String deptName;
    /**
     * FND_DEPARTMENT.REMARK
     * 描述
     */
    private String remark;

    /**
     * FND_DEPARTMENT.ORG_NAME
     * 单位名称
     */
    private String orgName;

    /**
     * FND_DEPARTMENT.LINK_MAN_TEL
     * 联系电话
     */
    private String linkManTel;

    /**
     * FND_DEPARTMENT.LINK_MAN_FAX
     * 传真
     */
    private String linkManFax;

    /**
     * FND_DEPARTMENT.LINK_MAN_NAME
     * 联系人
     */
    private String linkManName;

    /**
     * FND_DEPARTMENT.DEPAT_MANAGE_MAN
     * 部门负责人
     */
    private String depatManageMan;

    /**
     * This method returns the value of the database column
	 *	FND_DEPARTMENT.DEPT_CODE (部门代码)
     * @return the value of FND_DEPARTMENT.DEPT_CODE
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DEPARTMENT.DEPT_CODE (部门代码)
     * @param deptCode the value for FND_DEPARTMENT.DEPT_CODE
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method returns the value of the database column
	 *	FND_DEPARTMENT.ORG_CODE (机构代码)
     * @return the value of FND_DEPARTMENT.ORG_CODE
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DEPARTMENT.ORG_CODE (机构代码)
     * @param orgCode the value for FND_DEPARTMENT.ORG_CODE
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method returns the value of the database column
	 *	FND_DEPARTMENT.DEPT_NAME (部门名称)
     * @return the value of FND_DEPARTMENT.DEPT_NAME
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DEPARTMENT.DEPT_NAME (部门名称)
     * @param deptName the value for FND_DEPARTMENT.DEPT_NAME
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method returns the value of the database column
	 *	FND_DEPARTMENT.REMARK (描述)
     * @return the value of FND_DEPARTMENT.REMARK
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DEPARTMENT.REMARK (描述)
     * @param remark the value for FND_DEPARTMENT.REMARK
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method returns the value of the database column
	 *	FND_DEPARTMENT.ORG_NAME (单位名称)
     * @return the value of FND_DEPARTMENT.ORG_NAME
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DEPARTMENT.ORG_NAME (单位名称)
     * @param orgName the value for FND_DEPARTMENT.ORG_NAME
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method returns the value of the database column
	 *	FND_DEPARTMENT.LINK_MAN_TEL (联系电话)
     * @return the value of FND_DEPARTMENT.LINK_MAN_TEL
     */
    public String getLinkManTel() {
        return linkManTel;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DEPARTMENT.LINK_MAN_TEL (联系电话)
     * @param linkManTel the value for FND_DEPARTMENT.LINK_MAN_TEL
     */
    public void setLinkManTel(String linkManTel) {
        this.linkManTel = linkManTel == null ? null : linkManTel.trim();
    }

    /**
     * This method returns the value of the database column
	 *	FND_DEPARTMENT.LINK_MAN_FAX (传真)
     * @return the value of FND_DEPARTMENT.LINK_MAN_FAX
     */
    public String getLinkManFax() {
        return linkManFax;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DEPARTMENT.LINK_MAN_FAX (传真)
     * @param linkManFax the value for FND_DEPARTMENT.LINK_MAN_FAX
     */
    public void setLinkManFax(String linkManFax) {
        this.linkManFax = linkManFax == null ? null : linkManFax.trim();
    }

    /**
     * This method returns the value of the database column
	 *	FND_DEPARTMENT.LINK_MAN_NAME (联系人)
     * @return the value of FND_DEPARTMENT.LINK_MAN_NAME
     */
    public String getLinkManName() {
        return linkManName;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DEPARTMENT.LINK_MAN_NAME (联系人)
     * @param linkManName the value for FND_DEPARTMENT.LINK_MAN_NAME
     */
    public void setLinkManName(String linkManName) {
        this.linkManName = linkManName == null ? null : linkManName.trim();
    }

    /**
     * This method returns the value of the database column
	 *	FND_DEPARTMENT.DEPAT_MANAGE_MAN (部门负责人)
     * @return the value of FND_DEPARTMENT.DEPAT_MANAGE_MAN
     */
    public String getDepatManageMan() {
        return depatManageMan;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DEPARTMENT.DEPAT_MANAGE_MAN (部门负责人)
     * @param depatManageMan the value for FND_DEPARTMENT.DEPAT_MANAGE_MAN
     */
    public void setDepatManageMan(String depatManageMan) {
        this.depatManageMan = depatManageMan == null ? null : depatManageMan.trim();
    }

	@Override
	public String toString() {
		return "Department [deptCode=" + deptCode + ", orgCode=" + orgCode
				+ ", deptName=" + deptName + ", remark=" + remark
				+ ", orgName=" + orgName + ", linkManTel=" + linkManTel
				+ ", linkManFax=" + linkManFax + ", linkManName=" + linkManName
				+ ", depatManageMan=" + depatManageMan + "]";
	}
    
}