/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: DicValues.java
 * Creat Date: 2015-08-15 13:47:27
 */
package com.cloudwalk.ibis.model.system;

import java.io.Serializable;

/**
 * Class Name: DicValues<br/>
 * Description: This class corresponds to the table - FND_DIC_VALUES<br>
 * Create Date: 2015-08-15 13:47:27 <br/>
 */
public class DicValues implements Serializable {
    @Override
	public String toString() {
		return "DicValues [dicType=" + getDicType() + ",dicCode=" + getDicCode() + ",meaning=" + meaning + ", description=" + description
				+ ", enabledFlag=" + enabledFlag + "]";
	}
    
    /**
     * FND_DIC_VALUES.DIC_TYPE
     * 类型
     */
    private String dicType;

    /**
     * FND_DIC_VALUES.DIC_CODE
     * 编码
     */
    private String dicCode;

	/**
	 * serialVersionUID:序列化ID,缓存需要  
	 */
    private static final long serialVersionUID = -2341010126648788825L;

    /**
     * FND_DIC_VALUES.MEANING
     * 含义
     */
    private String meaning;

    /**
     * FND_DIC_VALUES.DESCRIPTION
     * 备注
     */
    private String description;

    /**
     * FND_DIC_VALUES.ENABLED_FLAG
     * 启用标志(1:启用，2：禁用）
     */
    private Integer enabledFlag;
    
    /**
     * 字典类型名称
     */
    private String descs;   

	public String getDescs() {
		return descs;
	}

	public void setDescs(String descs) {
		this.descs = descs;
	}

	/**
     * This method returns the value of the database column
	 *	FND_DIC_VALUES.DIC_TYPE (类型)
     * @return the value of FND_DIC_VALUES.DIC_TYPE
     */
    public String getDicType() {
        return dicType;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DIC_VALUES.DIC_TYPE (类型)
     * @param dicType the value for FND_DIC_VALUES.DIC_TYPE
     */
    public void setDicType(String dicType) {
        this.dicType = dicType;
    }

    /**
     * This method returns the value of the database column
	 *	FND_DIC_VALUES.DIC_CODE (编码)
     * @return the value of FND_DIC_VALUES.DIC_CODE
     */
    public String getDicCode() {
        return dicCode;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DIC_VALUES.DIC_CODE (编码)
     * @param dicCode the value for FND_DIC_VALUES.DIC_CODE
     */
    public void setDicCode(String dicCode) {
        this.dicCode = dicCode == null ? null : dicCode.trim();
    }

    /**
     * This method returns the value of the database column
	 *	FND_DIC_VALUES.MEANING (含义)
     * @return the value of FND_DIC_VALUES.MEANING
     */
    public String getMeaning() {
        return meaning;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DIC_VALUES.MEANING (含义)
     * @param meaning the value for FND_DIC_VALUES.MEANING
     */
    public void setMeaning(String meaning) {
        this.meaning = meaning == null ? null : meaning.trim();
    }

    /**
     * This method returns the value of the database column
	 *	FND_DIC_VALUES.DESCRIPTION (备注)
     * @return the value of FND_DIC_VALUES.DESCRIPTION
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DIC_VALUES.DESCRIPTION (备注)
     * @param description the value for FND_DIC_VALUES.DESCRIPTION
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method returns the value of the database column
	 *	FND_DIC_VALUES.ENABLED_FLAG (启用标志(1:启用，2：禁用）)
     * @return the value of FND_DIC_VALUES.ENABLED_FLAG
     */
    public Integer getEnabledFlag() {
        return enabledFlag;
    }

    /**
     * This method sets the value of the database column
	 *	FND_DIC_VALUES.ENABLED_FLAG (启用标志(1:启用，2：禁用）)
     * @param enabledFlag the value for FND_DIC_VALUES.ENABLED_FLAG
     */
    public void setEnabledFlag(Integer enabledFlag) {
        this.enabledFlag = enabledFlag;
    }
}