/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: Group.java
 * Creat Date: 2015-08-15 17:22:16
 */
package com.cloudwalk.ibis.model.system;

import java.io.Serializable;
import java.util.Date;

import com.cloudwalk.common.util.ObjectUtils;

/**
 * Class Name: Group<br/>
 * Description: This class corresponds to the table - FND_GROUP<br>
 * Create Date: 2015-08-15 17:22:16 <br/>
 */
public class Group implements Serializable {


	@Override
	public String toString() {
		return "Group [groupId=" + groupId + ", legalOrgCode=" + legalOrgCode
				+ ", groupCname=" + groupCname + ", groupEname=" + groupEname
				+ ", groupLevel=" + groupLevel + ", issys=" + issys
				+ ", remark=" + remark + ", userId=" + userId + ", createDate="
				+ createDate + "]";
	}

	/**
	 * serialVersionUID:序列化ID,缓存需要
	 */
	private static final long serialVersionUID = -5738940223795910265L;
	
	public Group() {
		String uuid = ObjectUtils.createUUID();
		this.groupId = uuid;
	}

	/**
	 * FND_GROUP.GROUP_ID 角色ID
	 */
	private String groupId;

	/**
	 * LEGAL_ORG_CODE 法人机构编码
	 */
	private String legalOrgCode;
	
	/**
	 * 机构名称
	 */
	private String orgName;
	
	/**
	 * FND_GROUP.GROUP_CNAME 角色中文名
	 */
	private String groupCname;

	/**
	 * FND_GROUP.GROUP_ENAME 角色英文名
	 */
	private String groupEname;

	/**
	 * FND_GROUP.GROUP_LEVEL 角色级别(1-总行级，2-分行级，3-分行级，4-网点级)
	 */
	private Integer groupLevel;

	/**
	 * FND_GROUP.ISSYS 用户角色是否是超级角色(1-不是，2-是)
	 */
	private Integer issys;

	/**
	 * FND_GROUP.REMARK 备注
	 */
	private String remark;

	/**
	 * 用户id
	 */
	private String userId;
	
	/**
	 * 创建时间
	 */
	private Date createDate;

	/**
	 * This method returns the value of the database column
	 * FND_GROUP.GROUP_CNAME (角色中文名)
	 *
	 * @return the value of FND_GROUP.GROUP_CNAME
	 */
	public String getGroupCname() {
		return groupCname;
	}

	/**
	 * This method returns the value of the database column
	 * FND_GROUP.GROUP_ENAME (角色英文名)
	 *
	 * @return the value of FND_GROUP.GROUP_ENAME
	 */
	public String getGroupEname() {
		return groupEname;
	}

	/**
	 * This method returns the value of the database column FND_GROUP.GROUP_ID
	 * (角色ID)
	 *
	 * @return the value of FND_GROUP.GROUP_ID
	 */
	public String getGroupId() {
		return groupId;
	}

	/**
	 * This method returns the value of the database column
	 * FND_GROUP.GROUP_LEVEL (角色级别(1-总行级，2-分行级，3-分行级，4-网点级))
	 *
	 * @return the value of FND_GROUP.GROUP_LEVEL
	 */
	public Integer getGroupLevel() {
		return groupLevel;
	}

	/**
	 * This method returns the value of the database column FND_GROUP.ISSYS
	 * (用户角色是否是超级角色(1-不是，2-是))
	 *
	 * @return the value of FND_GROUP.ISSYS
	 */
	public Integer getIssys() {
		return issys;
	}

	/**
	 * This method returns the value of the database column FND_GROUP.REMARK
	 * (备注)
	 *
	 * @return the value of FND_GROUP.REMARK
	 */
	public String getRemark() {
		return remark;
	}

	public String getUserId() {
		return userId;
	}

	/**
	 * This method sets the value of the database column FND_GROUP.GROUP_CNAME
	 * (角色中文名)
	 *
	 * @param groupCname
	 *            the value for FND_GROUP.GROUP_CNAME
	 */
	public void setGroupCname(String groupCname) {
		this.groupCname = groupCname == null ? null : groupCname.trim();
	}

	/**
	 * This method sets the value of the database column FND_GROUP.GROUP_ENAME
	 * (角色英文名)
	 *
	 * @param groupEname
	 *            the value for FND_GROUP.GROUP_ENAME
	 */
	public void setGroupEname(String groupEname) {
		this.groupEname = groupEname == null ? null : groupEname.trim();
	}

	/**
	 * This method sets the value of the database column FND_GROUP.GROUP_ID
	 * (角色ID)
	 *
	 * @param groupId
	 *            the value for FND_GROUP.GROUP_ID
	 */
	public void setGroupId(String groupId) {
		this.groupId = groupId == null ? null : groupId.trim();
	}

	/**
	 * This method sets the value of the database column FND_GROUP.GROUP_LEVEL
	 * (角色级别(1-总行级，2-分行级，3-分行级，4-网点级))
	 *
	 * @param groupLevel
	 *            the value for FND_GROUP.GROUP_LEVEL
	 */
	public void setGroupLevel(Integer groupLevel) {
		this.groupLevel = groupLevel;
	}

	/**
	 * This method sets the value of the database column FND_GROUP.ISSYS
	 * (用户角色是否是超级角色(1-不是，2-是))
	 *
	 * @param issys
	 *            the value for FND_GROUP.ISSYS
	 */
	public void setIssys(Integer issys) {
		this.issys = issys;
	}

	/**
	 * This method sets the value of the database column FND_GROUP.REMARK (备注)
	 *
	 * @param remark
	 *            the value for FND_GROUP.REMARK
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getLegalOrgCode() {
		return legalOrgCode;
	}

	public void setLegalOrgCode(String legalOrgCode) {
		this.legalOrgCode = legalOrgCode;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}
	
	

}