/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: Group.java
 * Creat Date: 2015-08-15 17:22:16
 */
package com.cloudwalk.ibis.model.system;

import java.io.Serializable;
import java.util.Arrays;

/**
 * Class Name: GroupDto<br/>
 * Description: This class corresponds to the table - FND_GROUP<br>
 * Create Date: 2015-08-15 17:22:16 <br/>
 */
public class GroupDto implements Serializable {
	@Override
	public String toString() {
		return "GroupDto [groupId=" + Arrays.toString(groupId)
				+ ", groupCname=" + Arrays.toString(groupCname)
				+ ", groupEname=" + Arrays.toString(groupEname) + "]";
	}

	/**
	 * serialVersionUID:序列化ID,缓存需要
	 */
	private static final long serialVersionUID = -5738940223795910265L;

	/**
	 * 法人机构编码
	 */
	private String legalOrgCode;
	
	/**
	 * FND_GROUP.GROUP_ID 角色ID
	 */
	private String[] groupId;

	/**
	 * FND_GROUP.GROUP_CNAME 角色中文名
	 */
	private String[] groupCname;

	/**
	 * FND_GROUP.GROUP_ENAME 角色英文名
	 */
	private String[] groupEname;

	public String[] getGroupCname() {
		return groupCname;
	}

	public String[] getGroupEname() {
		return groupEname;
	}

	public String[] getGroupId() {
		return groupId;
	}

	public void setGroupCname(String[] groupCname) {
		this.groupCname = groupCname;
	}

	public void setGroupEname(String[] groupEname) {
		this.groupEname = groupEname;
	}

	public void setGroupId(String[] groupId) {
		this.groupId = groupId;
	}

	public String getLegalOrgCode() {
		return legalOrgCode;
	}

	public void setLegalOrgCode(String legalOrgCode) {
		this.legalOrgCode = legalOrgCode;
	}
	
}