/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: Organization.java
 * Creat Date: 2015-08-15 11:30:16
 */
package com.cloudwalk.ibis.model.system;

import java.io.Serializable;
import java.util.List;

/**
 * Class Name: Organization<br/>
 * Description: This class corresponds to the table - FND_ORGANIZATION<br>
 * Create Date: 2015-08-15 11:30:16 <br/>
 */
public class Organization implements Serializable {
	/**
	 * serialVersionUID:序列化ID,缓存需要
	 */
	private static final long serialVersionUID = 8523712218912651339L;

	private String state = "closed"; // 属性展开状态

	/**
	 * FND_ORGANIZATION.ORG_CODE 机构代码
	 */
	private String orgCode;
	
	/**
	 * 机构代码参数
	 */
	private String orgCodeParam;
	
	/**
	 * ORG_CODE_PATH  机构代码全路径
	 */
	private String orgCodePath;
	/**
	 * FND_ORGANIZATION.ORG_LEVEL 机构级别(1 总行/2 支行/3 网点)
	 */
	private String orgLevel;
	/**
	 * LEGAL_STATUS 是否法人 1：是 0：否
	 */
	private Integer legalStatus;
	/**
	 * FND_ORGANIZATION.ORG_NAME 名称
	 */
	private String orgName;
	/**
	 * ORG_ANAME 机构全名
	 */
	private String orgAname;
	/**
	 * FND_ORGANIZATION.ADDRESS 地址
	 */
	private String address;

	/**
	 * FND_ORGANIZATION.ZIPCODE 邮编
	 */
	private String zipcode;
	/**
	 * FND_ORGANIZATION.TELEPHONE 电话号码
	 */
	private String telephone;

	/**
	 * FND_ORGANIZATION.FAX 传真
	 */
	private String fax;
	/**
	 * FND_ORGANIZATION.STATUS 经营状态(1 正常 2 暂停)
	 */
	private Integer status;

	/**
	 * FND_ORGANIZATION.PARENT_CODE 上级机构代码
	 */
	private String parentCode;

	/**
	 * FND_ORGANIZATION.LINK_MAN_NAME 联系人姓名
	 */
	private String linkManName;

	/**
	 * FND_ORGANIZATION.LINK_MAN_DEPT 部门
	 */
	private String linkManDept;

	/**
	 * FND_ORGANIZATION.LINK_MAN_POS 职务
	 */
	private String linkManPos;

	/**
	 * FND_ORGANIZATION.LINK_MAN_TEL 联系人电话
	 */
	private String linkManTel;

	/**
	 * FND_ORGANIZATION.LINK_MAN_FAX 联系人传真
	 */
	private String linkManFax;

	/**
	 * FND_ORGANIZATION.LINK_MAN_EMAIL 联系人EMAIL
	 */
	private String linkManEmail;

	/**
	 * FND_ORGANIZATION.AREA_ID 区域代码
	 */
	private String areaId;

	/**
	 * FND_ORGANIZATION.REMARK 描述
	 */
	private String remark;

	// 用户树形展示的子集合
	private List<Organization> children;
	
	private String parentOrgLevel;

	public String getParentOrgLevel() {
		return parentOrgLevel;
	}

	public void setParentOrgLevel(String parentOrgLevel) {
		this.parentOrgLevel = parentOrgLevel;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.ADDRESS (地址)
	 *
	 * @return the value of FND_ORGANIZATION.ADDRESS
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.AREA_ID (区域代码)
	 *
	 * @return the value of FND_ORGANIZATION.AREA_ID
	 */
	public String getAreaId() {
		return areaId;
	}

	public List<Organization> getChildren() {
		return children;
	}

	/**
	 * This method returns the value of the database column FND_ORGANIZATION.FAX
	 * (传真)
	 *
	 * @return the value of FND_ORGANIZATION.FAX
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.LINK_MAN_DEPT (部门)
	 *
	 * @return the value of FND_ORGANIZATION.LINK_MAN_DEPT
	 */
	public String getLinkManDept() {
		return linkManDept;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.LINK_MAN_EMAIL (联系人EMAIL)
	 *
	 * @return the value of FND_ORGANIZATION.LINK_MAN_EMAIL
	 */
	public String getLinkManEmail() {
		return linkManEmail;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.LINK_MAN_FAX (联系人传真)
	 *
	 * @return the value of FND_ORGANIZATION.LINK_MAN_FAX
	 */
	public String getLinkManFax() {
		return linkManFax;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.LINK_MAN_NAME (联系人姓名)
	 *
	 * @return the value of FND_ORGANIZATION.LINK_MAN_NAME
	 */
	public String getLinkManName() {
		return linkManName;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.LINK_MAN_POS (职务)
	 *
	 * @return the value of FND_ORGANIZATION.LINK_MAN_POS
	 */
	public String getLinkManPos() {
		return linkManPos;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.LINK_MAN_TEL (联系人电话)
	 *
	 * @return the value of FND_ORGANIZATION.LINK_MAN_TEL
	 */
	public String getLinkManTel() {
		return linkManTel;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.ORG_CODE (机构代码)
	 *
	 * @return the value of FND_ORGANIZATION.ORG_CODE
	 */
	public String getOrgCode() {
		return orgCode;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.ORG_LEVEL (机构级别(1 总行/2 支行/3 网点))
	 *
	 * @return the value of FND_ORGANIZATION.ORG_LEVEL
	 */
	public String getOrgLevel() {
		return orgLevel;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.ORG_NAME (名称)
	 *
	 * @return the value of FND_ORGANIZATION.ORG_NAME
	 */
	public String getOrgName() {
		return orgName;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.PARENT_CODE (上级机构代码)
	 *
	 * @return the value of FND_ORGANIZATION.PARENT_CODE
	 */
	public String getParentCode() {
		return parentCode;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.REMARK (描述)
	 *
	 * @return the value of FND_ORGANIZATION.REMARK
	 */
	public String getRemark() {
		return remark;
	}

	public String getState() {
		return state;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.STATUS (经营状态(1 正常 2 暂停))
	 *
	 * @return the value of FND_ORGANIZATION.STATUS
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.TELEPHONE (电话号码)
	 *
	 * @return the value of FND_ORGANIZATION.TELEPHONE
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method returns the value of the database column
	 * FND_ORGANIZATION.ZIPCODE (邮编)
	 *
	 * @return the value of FND_ORGANIZATION.ZIPCODE
	 */
	public String getZipcode() {
		return zipcode;
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.ADDRESS (地址)
	 *
	 * @param address
	 *            the value for FND_ORGANIZATION.ADDRESS
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.AREA_ID (区域代码)
	 *
	 * @param areaId
	 *            the value for FND_ORGANIZATION.AREA_ID
	 */
	public void setAreaId(String areaId) {
		this.areaId = areaId == null ? null : areaId.trim();
	}

	public void setChildren(List<Organization> children) {
		this.children = children;
	}

	/**
	 * This method sets the value of the database column FND_ORGANIZATION.FAX
	 * (传真)
	 *
	 * @param fax
	 *            the value for FND_ORGANIZATION.FAX
	 */
	public void setFax(String fax) {
		this.fax = fax == null ? null : fax.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.LINK_MAN_DEPT (部门)
	 *
	 * @param linkManDept
	 *            the value for FND_ORGANIZATION.LINK_MAN_DEPT
	 */
	public void setLinkManDept(String linkManDept) {
		this.linkManDept = linkManDept == null ? null : linkManDept.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.LINK_MAN_EMAIL (联系人EMAIL)
	 *
	 * @param linkManEmail
	 *            the value for FND_ORGANIZATION.LINK_MAN_EMAIL
	 */
	public void setLinkManEmail(String linkManEmail) {
		this.linkManEmail = linkManEmail == null ? null : linkManEmail.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.LINK_MAN_FAX (联系人传真)
	 *
	 * @param linkManFax
	 *            the value for FND_ORGANIZATION.LINK_MAN_FAX
	 */
	public void setLinkManFax(String linkManFax) {
		this.linkManFax = linkManFax == null ? null : linkManFax.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.LINK_MAN_NAME (联系人姓名)
	 *
	 * @param linkManName
	 *            the value for FND_ORGANIZATION.LINK_MAN_NAME
	 */
	public void setLinkManName(String linkManName) {
		this.linkManName = linkManName == null ? null : linkManName.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.LINK_MAN_POS (职务)
	 *
	 * @param linkManPos
	 *            the value for FND_ORGANIZATION.LINK_MAN_POS
	 */
	public void setLinkManPos(String linkManPos) {
		this.linkManPos = linkManPos == null ? null : linkManPos.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.LINK_MAN_TEL (联系人电话)
	 *
	 * @param linkManTel
	 *            the value for FND_ORGANIZATION.LINK_MAN_TEL
	 */
	public void setLinkManTel(String linkManTel) {
		this.linkManTel = linkManTel == null ? null : linkManTel.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.ORG_CODE (机构代码)
	 *
	 * @param orgCode
	 *            the value for FND_ORGANIZATION.ORG_CODE
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode == null ? null : orgCode.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.ORG_LEVEL (机构级别(1 总行/2 支行/3 网点))
	 *
	 * @param orgLevel
	 *            the value for FND_ORGANIZATION.ORG_LEVEL
	 */
	public void setOrgLevel(String orgLevel) {
		this.orgLevel = orgLevel;
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.ORG_NAME (名称)
	 *
	 * @param orgName
	 *            the value for FND_ORGANIZATION.ORG_NAME
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName == null ? null : orgName.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.PARENT_CODE (上级机构代码)
	 *
	 * @param parentCode
	 *            the value for FND_ORGANIZATION.PARENT_CODE
	 */
	public void setParentCode(String parentCode) {
		this.parentCode = parentCode == null ? null : parentCode.trim();
	}

	/**
	 * This method sets the value of the database column FND_ORGANIZATION.REMARK
	 * (描述)
	 *
	 * @param remark
	 *            the value for FND_ORGANIZATION.REMARK
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method sets the value of the database column FND_ORGANIZATION.STATUS
	 * (经营状态(1 正常 2 暂停))
	 *
	 * @param status
	 *            the value for FND_ORGANIZATION.STATUS
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.TELEPHONE (电话号码)
	 *
	 * @param telephone
	 *            the value for FND_ORGANIZATION.TELEPHONE
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone == null ? null : telephone.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_ORGANIZATION.ZIPCODE (邮编)
	 *
	 * @param zipcode
	 *            the value for FND_ORGANIZATION.ZIPCODE
	 */
	public void setZipcode(String zipcode) {
		this.zipcode = zipcode == null ? null : zipcode.trim();
	}

	public String getOrgCodePath() {
		return orgCodePath;
	}

	public void setOrgCodePath(String orgCodePath) {
		this.orgCodePath = orgCodePath;
	}

	public Integer getLegalStatus() {
		return legalStatus;
	}

	public void setLegalStatus(Integer legalStatus) {
		this.legalStatus = legalStatus;
	}

	public String getOrgAname() {
		return orgAname;
	}

	public void setOrgAname(String orgAname) {
		this.orgAname = orgAname;
	}	

	public String getOrgCodeParam() {
		return orgCodeParam;
	}

	public void setOrgCodeParam(String orgCodeParam) {
		this.orgCodeParam = orgCodeParam;
	}

	@Override
	public String toString() {
		return "Organization [state=" + state + ", orgCode=" + orgCode
				+ ", orgCodePath=" + orgCodePath + ", orgLevel=" + orgLevel
				+ ", legalStatus=" + legalStatus + ", orgName=" + orgName
				+ ", orgAname=" + orgAname + ", address=" + address
				+ ", zipcode=" + zipcode + ", telephone=" + telephone
				+ ", fax=" + fax + ", status=" + status + ", parentCode="
				+ parentCode + ", linkManName=" + linkManName
				+ ", linkManDept=" + linkManDept + ", linkManPos=" + linkManPos
				+ ", linkManTel=" + linkManTel + ", linkManFax=" + linkManFax
				+ ", linkManEmail=" + linkManEmail + ", areaId=" + areaId
				+ ", remark=" + remark + ", children=" + children + "]";
	}

}