/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: Resources.java
 * Creat Date: 2015-08-15 11:30:16
 */
package com.cloudwalk.ibis.model.system;

import java.io.Serializable;
import java.util.List;

import com.cloudwalk.common.util.ObjectUtils;

/**
 * Class Name: Resources<br/>
 * Description: This class corresponds to the table - FND_RESOURCES<br>
 * Create Date: 2015-08-15 11:30:16 <br/>
 */
public class Resources implements Serializable {
	@Override
	public String toString() {
		return "Resources [authorityId=" + authorityId + ", state=" + state
				+ ", resourceId=" + resourceId + ", resourceParentId="
				+ resourceParentId + ", resourceParentName="
				+ resourceParentName + ", resourceName=" + resourceName
				+ ", resourceType=" + resourceType + ", resourceDesc="
				+ resourceDesc + ", resourceUrl=" + resourceUrl + ", priority="
				+ priority + ", enabled=" + enabled + ", issys=" + issys
				+ ", resourceImage=" + resourceImage + ", children=" + children
				+ "]";
	}

	/**
	 * serialVersionUID:序列化ID,缓存需要
	 */
	private static final long serialVersionUID = 3590266306947526015L;
	
	public Resources() {
		String uuid = ObjectUtils.createUUID();
		this.resourceId = uuid;
	}

	private String authorityId;

	/**
	 * 资源的状态:open or closed
	 */
	private String state;

	/**
	 * FND_RESOURCES.RESOURCE_ID 资源ID
	 */
	private String resourceId;

	/**
	 * FND_RESOURCES.RESOURCE_PARENT_ID 父资源ID
	 */
	private String resourceParentId;

	/**
	 * 父级资源名称
	 */
	private String resourceParentName;

	/**
	 * FND_RESOURCES.RESOURCE_NAME 资源名称
	 */
	private String resourceName;

	/**
	 * FND_RESOURCES.RESOURCE_TYPE 资源类型（1：菜单，2：按键）
	 */
	private String resourceType;

	/**
	 * FND_RESOURCES.RESOURCE_DESC 资源描述
	 */
	private String resourceDesc;

	/**
	 * FND_RESOURCES.RESOURCE_URL 资源链接
	 */
	private String resourceUrl;

	/**
	 * FND_RESOURCES.PRIORITY 资源优先级
	 */
	private Integer priority;

	/**
	 * FND_RESOURCES.ENABLED 资源是否可用(1 正常 2 暂停)
	 */
	private Integer enabled;

	/**
	 * FND_RESOURCES.ISSYS 是否是超级资源(1-不是，2-是)
	 */
	private Integer issys;

	/**
	 * FND_RESOURCES.RESOURCE_IMAGE 资源图片
	 */
	private String resourceImage;

	private List<Resources> children;

	public String getAuthorityId() {
		return authorityId;
	}

	public List<Resources> getChildren() {
		return children;
	}

	/**
	 * This method returns the value of the database column
	 * FND_RESOURCES.ENABLED (资源是否可用(1 正常 2 暂停))
	 *
	 * @return the value of FND_RESOURCES.ENABLED
	 */
	public Integer getEnabled() {
		return enabled;
	}

	/**
	 * This method returns the value of the database column FND_RESOURCES.ISSYS
	 * (是否是超级资源(1-不是，2-是))
	 *
	 * @return the value of FND_RESOURCES.ISSYS
	 */
	public Integer getIssys() {
		return issys;
	}

	/**
	 * This method returns the value of the database column
	 * FND_RESOURCES.PRIORITY (资源优先级)
	 *
	 * @return the value of FND_RESOURCES.PRIORITY
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method returns the value of the database column
	 * FND_RESOURCES.RESOURCE_DESC (资源描述)
	 *
	 * @return the value of FND_RESOURCES.RESOURCE_DESC
	 */
	public String getResourceDesc() {
		return resourceDesc;
	}

	/**
	 * This method returns the value of the database column
	 * FND_RESOURCES.RESOURCE_ID (资源ID)
	 *
	 * @return the value of FND_RESOURCES.RESOURCE_ID
	 */
	public String getResourceId() {
		return resourceId;
	}

	/**
	 * This method returns the value of the database column
	 * FND_RESOURCES.RESOURCE_IMAGE (资源图片)
	 *
	 * @return the value of FND_RESOURCES.RESOURCE_IMAGE
	 */
	public String getResourceImage() {
		return resourceImage;
	}

	/**
	 * This method returns the value of the database column
	 * FND_RESOURCES.RESOURCE_NAME (资源名称)
	 *
	 * @return the value of FND_RESOURCES.RESOURCE_NAME
	 */
	public String getResourceName() {
		return resourceName;
	}

	/**
	 * This method returns the value of the database column
	 * FND_RESOURCES.RESOURCE_PARENT_ID (父资源ID)
	 *
	 * @return the value of FND_RESOURCES.RESOURCE_PARENT_ID
	 */
	public String getResourceParentId() {
		return resourceParentId;
	}

	public String getResourceParentName() {
		return resourceParentName;
	}

	/**
	 * This method returns the value of the database column
	 * FND_RESOURCES.RESOURCE_TYPE (资源类型（1：菜单，2：按键）)
	 *
	 * @return the value of FND_RESOURCES.RESOURCE_TYPE
	 */
	public String getResourceType() {
		return resourceType;
	}

	/**
	 * This method returns the value of the database column
	 * FND_RESOURCES.RESOURCE_URL (资源链接)
	 *
	 * @return the value of FND_RESOURCES.RESOURCE_URL
	 */
	public String getResourceUrl() {
		return resourceUrl;
	}

	public String getState() {
		return state;
	}

	public void setAuthorityId(String authorityId) {
		this.authorityId = authorityId;
	}

	public void setChildren(List<Resources> children) {
		this.children = children;
	}

	/**
	 * This method sets the value of the database column FND_RESOURCES.ENABLED
	 * (资源是否可用(1 正常 2 暂停))
	 *
	 * @param enabled
	 *            the value for FND_RESOURCES.ENABLED
	 */
	public void setEnabled(Integer enabled) {
		this.enabled = enabled;
	}

	/**
	 * This method sets the value of the database column FND_RESOURCES.ISSYS
	 * (是否是超级资源(1-不是，2-是))
	 *
	 * @param issys
	 *            the value for FND_RESOURCES.ISSYS
	 */
	public void setIssys(Integer issys) {
		this.issys = issys;
	}

	/**
	 * This method sets the value of the database column FND_RESOURCES.PRIORITY
	 * (资源优先级)
	 *
	 * @param priority
	 *            the value for FND_RESOURCES.PRIORITY
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method sets the value of the database column
	 * FND_RESOURCES.RESOURCE_DESC (资源描述)
	 *
	 * @param resourceDesc
	 *            the value for FND_RESOURCES.RESOURCE_DESC
	 */
	public void setResourceDesc(String resourceDesc) {
		this.resourceDesc = resourceDesc == null ? null : resourceDesc.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_RESOURCES.RESOURCE_ID (资源ID)
	 *
	 * @param resourceId
	 *            the value for FND_RESOURCES.RESOURCE_ID
	 */
	public void setResourceId(String resourceId) {
		this.resourceId = resourceId == null ? null : resourceId.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_RESOURCES.RESOURCE_IMAGE (资源图片)
	 *
	 * @param resourceImage
	 *            the value for FND_RESOURCES.RESOURCE_IMAGE
	 */
	public void setResourceImage(String resourceImage) {
		this.resourceImage = resourceImage == null ? null : resourceImage
				.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_RESOURCES.RESOURCE_NAME (资源名称)
	 *
	 * @param resourceName
	 *            the value for FND_RESOURCES.RESOURCE_NAME
	 */
	public void setResourceName(String resourceName) {
		this.resourceName = resourceName == null ? null : resourceName.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_RESOURCES.RESOURCE_PARENT_ID (父资源ID)
	 *
	 * @param resourceParentId
	 *            the value for FND_RESOURCES.RESOURCE_PARENT_ID
	 */
	public void setResourceParentId(String resourceParentId) {
		this.resourceParentId = resourceParentId == null ? null
				: resourceParentId.trim();
	}

	public void setResourceParentName(String resourceParentName) {
		this.resourceParentName = resourceParentName;
	}

	/**
	 * This method sets the value of the database column
	 * FND_RESOURCES.RESOURCE_TYPE (资源类型（1：菜单，2：按键）)
	 *
	 * @param resourceType
	 *            the value for FND_RESOURCES.RESOURCE_TYPE
	 */
	public void setResourceType(String resourceType) {
		this.resourceType = resourceType == null ? null : resourceType.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_RESOURCES.RESOURCE_URL (资源链接)
	 *
	 * @param resourceUrl
	 *            the value for FND_RESOURCES.RESOURCE_URL
	 */
	public void setResourceUrl(String resourceUrl) {
		this.resourceUrl = resourceUrl == null ? null : resourceUrl.trim();
	}

	public void setState(String state) {
		this.state = state;
	}

}