/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: User.java
 * Creat Date: 2015-08-15 11:30:16
 */
package com.cloudwalk.ibis.model.system;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;

import com.cloudwalk.common.util.ObjectUtils;

/**
 * Class Name: User<br/>
 * Description: This class corresponds to the table - FND_USER<br>
 * Create Date: 2015-08-15 11:30:16 <br/>
 */
public class User implements Serializable {
	

	@Override
	public String toString() {
		return "User [userId=" + userId + ", deptCode=" + deptCode
				+ ", orgLevel=" + orgLevel + ", deptName=" + deptName
				+ ", workCode=" + workCode + ", orgCode=" + orgCode
				+ ", orgCodePath=" + orgCodePath + ", legalOrgCode="
				+ legalOrgCode + ", orgName=" + orgName + ", orgAName="
				+ orgAName + ", userLoginName=" + userLoginName + ", userPwd="
				+ userPwd + ", userStatus=" + userStatus + ", userName="
				+ userName + ", userRank=" + userRank + ", email=" + email
				+ ", telephone=" + telephone + ", pictureName=" + pictureName
				+ ", remark=" + remark + ", createDate=" + createDate
				+ ", updateDate=" + updateDate + ", deleteDate=" + deleteDate
				+ ", roleName=" + roleName + ", authUrllist=" + authUrllist
				+ ", btnMapList=" + btnMapList + ", resourcesList="
				+ resourcesList + ", authUrlMap=" + authUrlMap
				+ ", randCheckCode=" + randCheckCode + "]";
	}

	/**
	 * serialVersionUID:序列化ID,缓存需要
	 */
	private static final long serialVersionUID = -5737387281932315813L;
	
	public User() {
		String uuid = ObjectUtils.createUUID();
		this.userId = uuid;
	}

	/**
	 * FND_USER.USER_ID 用户ID
	 */
	private String userId;

	/**
	 * FND_USER.DEPT_CODE 部门代码
	 */
	private String deptCode;
	/**
	 * ORG_LEVEL 机构级别(数据字典)
	 */
	private String orgLevel;
	/**
	 * 部门名称
	 */
	private String deptName;

	/**
	 * FND_USER.WORK_CODE 用户员工号
	 */
	private String workCode;

	/**
	 * 机构编码
	 */
	private String orgCode;
	
	/**
	 * 机构编码全路径
	 */
	private String orgCodePath;
	
	/**
	 * 法人机构编码全路径
	 */
	private String legalOrgCode;
	
	/**
	 * 法人机构编码
	 */
	private String legalCode;

	/**
	 * 机构名称
	 */
	private String orgName;
	
	/**
	 * 机构全名称
	 */
	private String orgAName;

	/**
	 * FND_USER.USER_LOGIN_NAME 用户登录名
	 */
	private String userLoginName;

	/**
	 * FND_USER.USER_PWD 口令
	 */
	private String userPwd;

	/**
	 * FND_USER.USER_STATUS 用户状态(1 正常 2 暂停)
	 */
	private Integer userStatus;

	/**
	 * FND_USER.USER_NAME 全名
	 */
	private String userName;

	/**
	 * FND_USER.USER_RANK 职位
	 */
	private String userRank;

	/**
	 * FND_USER.EMAIL 邮件
	 */
	private String email;

	/**
	 * FND_USER.TELEPHONE 联系电话
	 */
	private String telephone;

	/**
	 * FND_USER.PICTURE_NAME 照片名称
	 */
	private String pictureName;

	/**
	 * FND_USER.REMARK 备注
	 */
	private String remark;

	/**
	 * FND_USER.CREATE_DATE 创建日期
	 */
	private Date createDate;

	/**
	 * FND_USER.UPDATE_DATE 修改日期
	 */
	private Date updateDate;

	/**
	 * FND_USER.DELETE_DATE 注销时间
	 */
	private Date deleteDate;

	/**
	 * 机构名称
	 */
	private String roleName;

	/**
	 * 当前用户的权限列表
	 */
	private List<String> authUrllist;

	/**
	 * 当前用户的按钮Map
	 */
	private Map<String, List<Resources>> btnMapList;

	/**
	 * 当前用户的菜单列表
	 */
	private List<Resources> resourcesList;

	/**
	 * 资源url，名称 map
	 */
	private Map<String, String> authUrlMap;
	
	/**
	 * 验证码
	 */
	private String randCheckCode;

	public List<String> getAuthUrllist() {
		return authUrllist;
	}

	public Map<String, String> getAuthUrlMap() {
		return authUrlMap;
	}

	/**
	 *
	 * getAuthUrlName:根据资源url获取对应的名称. <br/>
	 *
	 * @author:朱云飞 Date: 2015年8月31日 下午6:57:06
	 * @param url
	 * @return
	 * @since JDK 1.7
	 */
	public String getAuthUrlName(String url) {
		if (!ObjectUtils.isEmpty(authUrlMap)) {
			if (authUrlMap.containsKey(url)) {
				return authUrlMap.get(url);
			}
		}
		return "";
	}

	public Map<String, List<Resources>> getBtnMapList() {
		return btnMapList;
	}

	/**
	 * This method returns the value of the database column FND_USER.CREATE_DATE
	 * (创建日期)
	 *
	 * @return the value of FND_USER.CREATE_DATE
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method returns the value of the database column FND_USER.DELETE_DATE
	 * (注销时间)
	 *
	 * @return the value of FND_USER.DELETE_DATE
	 */
	public Date getDeleteDate() {
		return deleteDate;
	}

	/**
	 * This method returns the value of the database column FND_USER.DEPT_CODE
	 * (部门代码)
	 *
	 * @return the value of FND_USER.DEPT_CODE
	 */
	public String getDeptCode() {
		return deptCode;
	}

	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method returns the value of the database column FND_USER.EMAIL (邮件)
	 *
	 * @return the value of FND_USER.EMAIL
	 */
	public String getEmail() {
		return email;
	}

	public String getOrgCode() {
		return orgCode;
	}

	public String getOrgName() {
		return orgName;
	}

	/**
	 * This method returns the value of the database column
	 * FND_USER.PICTURE_NAME (照片名称)
	 *
	 * @return the value of FND_USER.PICTURE_NAME
	 */
	public String getPictureName() {
		return pictureName;
	}

	/**
	 * This method returns the value of the database column FND_USER.REMARK (备注)
	 *
	 * @return the value of FND_USER.REMARK
	 */
	public String getRemark() {
		return remark;
	}

	public List<Resources> getResourcesList() {
		return resourcesList;
	}

	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method returns the value of the database column FND_USER.TELEPHONE
	 * (联系电话)
	 *
	 * @return the value of FND_USER.TELEPHONE
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method returns the value of the database column FND_USER.UPDATE_DATE
	 * (修改日期)
	 *
	 * @return the value of FND_USER.UPDATE_DATE
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method returns the value of the database column FND_USER.USER_ID
	 * (用户ID)
	 *
	 * @return the value of FND_USER.USER_ID
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method returns the value of the database column
	 * FND_USER.USER_LOGIN_NAME (用户登录名)
	 *
	 * @return the value of FND_USER.USER_LOGIN_NAME
	 */
	public String getUserLoginName() {
		return userLoginName;
	}

	/**
	 * This method returns the value of the database column FND_USER.USER_NAME
	 * (全名)
	 *
	 * @return the value of FND_USER.USER_NAME
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method returns the value of the database column FND_USER.USER_PWD
	 * (口令)
	 *
	 * @return the value of FND_USER.USER_PWD
	 */
	public String getUserPwd() {
		return userPwd;
	}

	/**
	 * This method returns the value of the database column FND_USER.USER_RANK
	 * (职位)
	 *
	 * @return the value of FND_USER.USER_RANK
	 */
	public String getUserRank() {
		return userRank;
	}

	/**
	 * This method returns the value of the database column FND_USER.USER_STATUS
	 * (用户状态(1 正常 2 暂停))
	 *
	 * @return the value of FND_USER.USER_STATUS
	 */
	public Integer getUserStatus() {
		return userStatus;
	}

	/**
	 * This method returns the value of the database column FND_USER.WORK_CODE
	 * (用户员工号)
	 *
	 * @return the value of FND_USER.WORK_CODE
	 */
	public String getWorkCode() {
		return workCode;
	}

	public void setAuthUrllist(List<String> authUrllist) {
		this.authUrllist = authUrllist;
	}

	public void setAuthUrlMap(Map<String, String> authUrlMap) {
		this.authUrlMap = authUrlMap;
	}

	public void setBtnMapList(Map<String, List<Resources>> btnMapList) {
		this.btnMapList = btnMapList;
	}

	/**
	 * This method sets the value of the database column FND_USER.CREATE_DATE
	 * (创建日期)
	 *
	 * @param createDate
	 *            the value for FND_USER.CREATE_DATE
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method sets the value of the database column FND_USER.DELETE_DATE
	 * (注销时间)
	 *
	 * @param deleteDate
	 *            the value for FND_USER.DELETE_DATE
	 */
	public void setDeleteDate(Date deleteDate) {
		this.deleteDate = deleteDate;
	}

	/**
	 * This method sets the value of the database column FND_USER.DEPT_CODE
	 * (部门代码)
	 *
	 * @param deptCode
	 *            the value for FND_USER.DEPT_CODE
	 */
	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode == null ? null : deptCode.trim();
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/**
	 * This method sets the value of the database column FND_USER.EMAIL (邮件)
	 *
	 * @param email
	 *            the value for FND_USER.EMAIL
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	/**
	 * This method sets the value of the database column FND_USER.PICTURE_NAME
	 * (照片名称)
	 *
	 * @param pictureName
	 *            the value for FND_USER.PICTURE_NAME
	 */
	public void setPictureName(String pictureName) {
		this.pictureName = pictureName == null ? null : pictureName.trim();
	}

	/**
	 * This method sets the value of the database column FND_USER.REMARK (备注)
	 *
	 * @param remark
	 *            the value for FND_USER.REMARK
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	public void setResourcesList(List<Resources> resourcesList) {
		this.resourcesList = resourcesList;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method sets the value of the database column FND_USER.TELEPHONE
	 * (联系电话)
	 *
	 * @param telephone
	 *            the value for FND_USER.TELEPHONE
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone == null ? null : telephone.trim();
	}

	/**
	 * This method sets the value of the database column FND_USER.UPDATE_DATE
	 * (修改日期)
	 *
	 * @param updateDate
	 *            the value for FND_USER.UPDATE_DATE
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method sets the value of the database column FND_USER.USER_ID (用户ID)
	 *
	 * @param userId
	 *            the value for FND_USER.USER_ID
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method sets the value of the database column
	 * FND_USER.USER_LOGIN_NAME (用户登录名)
	 *
	 * @param userLoginName
	 *            the value for FND_USER.USER_LOGIN_NAME
	 */
	public void setUserLoginName(String userLoginName) {
		this.userLoginName = userLoginName == null ? null : userLoginName
				.trim();
	}

	/**
	 * This method sets the value of the database column FND_USER.USER_NAME (全名)
	 *
	 * @param userName
	 *            the value for FND_USER.USER_NAME
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method sets the value of the database column FND_USER.USER_PWD (口令)
	 *
	 * @param userPwd
	 *            the value for FND_USER.USER_PWD
	 */
	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd == null ? null : userPwd.trim();
	}

	/**
	 * This method sets the value of the database column FND_USER.USER_RANK (职位)
	 *
	 * @param userRank
	 *            the value for FND_USER.USER_RANK
	 */
	public void setUserRank(String userRank) {
		this.userRank = userRank == null ? null : userRank.trim();
	}

	/**
	 * This method sets the value of the database column FND_USER.USER_STATUS
	 * (用户状态(1 正常 2 暂停))
	 *
	 * @param userStatus
	 *            the value for FND_USER.USER_STATUS
	 */
	public void setUserStatus(Integer userStatus) {
		this.userStatus = userStatus;
	}

	/**
	 * This method sets the value of the database column FND_USER.WORK_CODE
	 * (用户员工号)
	 *
	 * @param workCode
	 *            the value for FND_USER.WORK_CODE
	 */
	public void setWorkCode(String workCode) {
		this.workCode = workCode == null ? null : workCode.trim();
	}

	public String getRandCheckCode() {
		return randCheckCode;
	}

	public void setRandCheckCode(String randCheckCode) {
		this.randCheckCode = randCheckCode;
	}

	public String getLegalOrgCode() {
		return legalOrgCode;
	}

	public void setLegalOrgCode(String legalOrgCode) {
		this.legalOrgCode = legalOrgCode;
		if(!StringUtils.isBlank(legalOrgCode)) {
			String[] legalOrgCodes = legalOrgCode.split("_");
			if(legalOrgCodes.length > 0) {
				this.legalCode = legalOrgCodes[legalOrgCodes.length-1];
			}
		}
	}

	public String getOrgAName() {
		return orgAName;
	}

	public void setOrgAName(String orgAName) {
		this.orgAName = orgAName;
	}

	public String getOrgCodePath() {
		return orgCodePath;
	}

	public void setOrgCodePath(String orgCodePath) {
		this.orgCodePath = orgCodePath;
	}

	public String getOrgLevel() {
		return orgLevel;
	}

	public void setOrgLevel(String orgLevel) {
		this.orgLevel = orgLevel;
	}

	public String getLegalCode() {
		return legalCode;
	}

	public void setLegalCode(String legalCode) {
		this.legalCode = legalCode;
	}
	
	
	
}