/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: PersonMapper.java
 * Creat Date: 2015-08-15 11:30:16
 */
package com.cloudwalk.ibis.repository.schedule;

import java.util.List;
import java.util.Map;

import com.cloudwalk.ibis.model.schedule.ScheduleEntity;
import com.cloudwalk.ibis.model.schedule.ScheduleRecordEntity;

/**
 * 定时任务mapper
 * @author zhuyf
 *
 */
public interface ScheduleMapper {
	
	/**
	 * 根据创建时间查询定时任务记录信息
	 * @return
	 */
	public List<ScheduleRecordEntity> selectScheduleRecordByDate(Map<String,Object> map);
	
	/**
	 * 插入定时任务记录信息
	 * @param se
	 * @return
	 */
	public int addScheduleRecord(ScheduleRecordEntity se);
	
	/**
	 * 添加定时任务信息
	 * @param se
	 * @return
	 */
	public int addSchedule(ScheduleEntity se);
	
	/**
	 * 分页查询定时任务
	 * @param map
	 * @return
	 */
	public List<ScheduleEntity> selectSchedulePage(Map<String, Object> map);
	
	/**
	 * 分页查询定时任务执行记录
	 * @param map
	 * @return
	 */
	public List<ScheduleRecordEntity> selectScheduleRecordPage(Map<String, Object> map);
	
	/**
	 * 根据任务编码查询定时任务
	 * @param taskCode 任务编码
	 */
	public List<ScheduleEntity> selectScheduleByCode(String taskCode);
	
	/**
	 * 更新定时任务状态
	 * @param se
	 * @return
	 */
	public int updateScheduleStatus(ScheduleEntity se);
	
	/**
	 * 完成定时任务
	 * @param se
	 * @return
	 */
	public int finishSchedule(ScheduleRecordEntity se);
	
	/**
	 * 更新任务信息
	 * @param se
	 * @return
	 */
	public int updateScheduleRecord(ScheduleRecordEntity se);
	
	
}