/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: DepartmentMapper.java
 * Creat Date: 2015-08-19 15:56:28
 */
package com.cloudwalk.ibis.repository.system;

import java.util.List;
import java.util.Map;

import org.springframework.cache.annotation.CachePut;
import org.springframework.dao.DataAccessException;

import com.cloudwalk.ibis.model.system.Department;
import com.google.code.ssm.api.InvalidateSingleCache;
import com.google.code.ssm.api.ParameterValueKeyProvider;
import com.google.code.ssm.api.ReadThroughMultiCache;
import com.google.code.ssm.api.ReadThroughSingleCache;
import com.google.code.ssm.api.UpdateSingleCache;

/**
 * Class Name: DepartmentMapper <br>
 * Description: This interface corresponds to the table - FND_DEPARTMENT <br>
 * Create Date: 2015-08-19 15:56:28 <br>
 */
public interface DepartmentMapper {
	/**
	 * Method: deleteByPrimaryKey(...) <br/>
	 * Delete record from table - FND_DEPARTMENT<br/>
	 * Param: deptCode (部门代码) , the paremeter can not empty. <br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_DEPARTMENT<br/>
	 * 2: DepartmentService call this method, then the realization method calls
	 * DepartmentMapper.xml to delete from database.<br/>
	 * 3: throws DataAccessException exception <br/>
	 * Remarks: If the method executed successfully, need to be removed
	 * Department object from memory cache Create Date: 2015-08-19 15:56:28
	 */
	@InvalidateSingleCache(namespace = "Department")
	int deleteByPrimaryKey(@ParameterValueKeyProvider String deptCode)
			throws DataAccessException;

	/**
	 * Method: insertSelective(...) <br/>
	 * Insert a record to table - FND_DEPARTMENT<br/>
	 * Param: record, the paremeter can not empty, for details please to see
	 * Department.java model file.<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_DEPARTMENT<br/>
	 * 2: DepartmentService call this method, then the realization method calls
	 * DepartmentMapper.xml to add record into database.<br/>
	 * 3: throws DataAccessException exception <br/>
	 * Create Date: 2015-08-19 15:56:28
	 */
	@CachePut(value = "Department")
	int insertSelective(Department record) throws DataAccessException;

	int isExistsChildUser(String deptCode) throws DataAccessException;

	/**
	 * Method: searchAll(...) <br/>
	 * Select some records from table - FND_DEPARTMENT <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_DEPARTMENT <br/>
	 * 2: DepartmentService call this method, then the realization method calls
	 * DepartmentMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Department correspondence from the
	 * cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-19 15:56:28
	 */
	@ReadThroughMultiCache(namespace = "Department", expiration = 30)
	List<Department> searchAll(Department record)
			throws DataAccessException;

	/**
	 * Method: searchAllByPage(...) <br/>
	 * Select some records from table by page- FND_DEPARTMENT <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_DEPARTMENT <br/>
	 * 2: DepartmentService call this method, then the realization method calls
	 * DepartmentMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Department correspondence from the
	 * cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-19 15:56:28
	 */
	@ReadThroughMultiCache(namespace = "Department", expiration = 30)
	List<Department> searchAllByPage(Map<String, Object> map)
			throws DataAccessException;

	/**
	 * Method: selectAll(...) <br/>
	 * Select some records from table - FND_DEPARTMENT <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_DEPARTMENT <br/>
	 * 2: DepartmentService call this method, then the realization method calls
	 * DepartmentMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Department correspondence from the
	 * cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-19 15:56:28
	 */
	@ReadThroughMultiCache(namespace = "Department", expiration = 30)
	List<Department> selectAll(Department record)
			throws DataAccessException;

	/**
	 * Method: selectAllByPage(...) <br/>
	 * Select some records from table by page- FND_DEPARTMENT <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_DEPARTMENT <br/>
	 * 2: DepartmentService call this method, then the realization method calls
	 * DepartmentMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Department correspondence from the
	 * cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-19 15:56:28
	 */
	@ReadThroughMultiCache(namespace = "Department", expiration = 30)
	List<Department> selectAllByPage(Map<String, Object> map)
			throws DataAccessException;

	/**
	 * Method: selectByPrimaryKey(...) <br/>
	 * Select a record from table - FND_DEPARTMENT <br/>
	 * Param: deptCode (部门代码) , the paremeter can not empty. <br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_DEPARTMENT <br/>
	 * 2: DepartmentService call this method, then the realization method calls
	 * DepartmentMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughSingleCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Department correspondence from the
	 * cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-19 15:56:28
	 */
	@ReadThroughSingleCache(namespace = "Department", expiration = 30)
	Department selectByPrimaryKey(String deptCode) throws DataAccessException;

	/**
	 * Method: selectCount(...) <br/>
	 * Select some records count from table - FND_DEPARTMENT <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records count<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_DEPARTMENT <br/>
	 * 2: DepartmentService call this method, then the realization method calls
	 * DepartmentMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Department correspondence from the
	 * cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-19 15:56:28
	 */
	int selectCount(Department record) throws DataAccessException;

	/**
	 * Method: updateByPrimaryKeySelective(...) <br/>
	 * Update record by primary key to table - FND_DEPARTMENT<br/>
	 * Param: record, the paremeter can not empty, for details please to see
	 * Department.java model file.<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_DEPARTMENT<br/>
	 * 2: DepartmentService call this method, then the realization method calls
	 * DepartmentMapper.xml to add record into database.<br/>
	 * 3: @UpdateSingleCache(namespace = "cache object name", expiration = cache
	 * expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Create Date: 2015-08-19 15:56:28
	 */
	@UpdateSingleCache(namespace = "Department", expiration = 30)
	int updateByPrimaryKeySelective(Department record) throws DataAccessException;
}