/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: GroupAuthRefMapper.java
 * Creat Date: 2015-08-15 11:30:16
 */
package com.cloudwalk.ibis.repository.system;

import java.util.List;
import java.util.Map;

import org.springframework.cache.annotation.CachePut;
import org.springframework.dao.DataAccessException;

import com.cloudwalk.ibis.model.system.GroupAuthRefKey;
import com.google.code.ssm.api.InvalidateSingleCache;
import com.google.code.ssm.api.ParameterValueKeyProvider;
import com.google.code.ssm.api.ReadThroughMultiCache;

/**
 * Class Name: GroupAuthRefMapper <br>
 * Description: This interface corresponds to the table - FND_GROUP_AUTH_REF <br>
 * Create Date: 2015-08-15 11:30:16 <br>
 */
public interface GroupAuthRefMapper {
	int deleteByGroupId(String groupId) throws DataAccessException;

	/**
	 * Method: deleteByPrimaryKey(...) <br/>
	 * Delete record from table - FND_GROUP_AUTH_REF<br/>
	 * Param: the key paremeter can not empty. <br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP_AUTH_REF<br/>
	 * 2: GroupAuthRefService call this method, then the realization method
	 * calls GroupAuthRefMapper.xml to delete from database.<br/>
	 * 3: throws DataAccessException exception <br/>
	 * Remarks: If the method executed successfully, need to be removed
	 * GroupAuthRef object from memory cache Create Date: 2015-08-15 11:30:16
	 */
	@InvalidateSingleCache(namespace = "GroupAuthRef")
	int deleteByPrimaryKey(@ParameterValueKeyProvider GroupAuthRefKey key)
			throws DataAccessException;

	/**
	 * Method: insertSelective(...) <br/>
	 * Insert a record to table - FND_GROUP_AUTH_REF<br/>
	 * Param: record, the paremeter can not empty, for details please to see
	 * GroupAuthRefKey.java model file.<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP_AUTH_REF<br/>
	 * 2: GroupAuthRefService call this method, then the realization method
	 * calls GroupAuthRefMapper.xml to add record into database.<br/>
	 * 3: throws DataAccessException exception <br/>
	 * Create Date: 2015-08-15 11:30:16
	 */
	@CachePut(value = "GroupAuthRef")
	int insertSelective(GroupAuthRefKey record) throws DataAccessException;

	int insertSelectiveBatch(List<GroupAuthRefKey> items)
			throws DataAccessException;

	/**
	 * Method: searchAll(...) <br/>
	 * Select some records from table - FND_GROUP_AUTH_REF <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP_AUTH_REF <br/>
	 * 2: GroupAuthRefService call this method, then the realization method
	 * calls GroupAuthRefMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get GroupAuthRef correspondence from
	 * the cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 11:30:16
	 */
	@ReadThroughMultiCache(namespace = "GroupAuthRef", expiration = 30)
	List<GroupAuthRefKey> searchAll(GroupAuthRefKey record)
			throws DataAccessException;

	/**
	 * Method: searchAllByPage(...) <br/>
	 * Select some records from table by page- FND_GROUP_AUTH_REF <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP_AUTH_REF <br/>
	 * 2: GroupAuthRefService call this method, then the realization method
	 * calls GroupAuthRefMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get GroupAuthRef correspondence from
	 * the cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 11:30:16
	 */
	@ReadThroughMultiCache(namespace = "GroupAuthRef", expiration = 30)
	List<GroupAuthRefKey> searchAllByPage(Map<String, Object> map)
			throws DataAccessException;

	/**
	 * Method: selectAll(...) <br/>
	 * Select some records from table - FND_GROUP_AUTH_REF <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP_AUTH_REF <br/>
	 * 2: GroupAuthRefService call this method, then the realization method
	 * calls GroupAuthRefMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get GroupAuthRef correspondence from
	 * the cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 11:30:16
	 */
	@ReadThroughMultiCache(namespace = "GroupAuthRef", expiration = 30)
	List<GroupAuthRefKey> selectAll(GroupAuthRefKey record)
			throws DataAccessException;

	/**
	 * Method: selectAllByPage(...) <br/>
	 * Select some records from table by page- FND_GROUP_AUTH_REF <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP_AUTH_REF <br/>
	 * 2: GroupAuthRefService call this method, then the realization method
	 * calls GroupAuthRefMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get GroupAuthRef correspondence from
	 * the cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 11:30:16
	 */
	@ReadThroughMultiCache(namespace = "GroupAuthRef", expiration = 30)
	List<GroupAuthRefKey> selectAllByPage(Map<String, Object> map)
			throws DataAccessException;

	/**
	 * Method: selectCount(...) <br/>
	 * Select some records count from table - FND_GROUP_AUTH_REF <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records count<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP_AUTH_REF <br/>
	 * 2: GroupAuthRefService call this method, then the realization method
	 * calls GroupAuthRefMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get GroupAuthRef correspondence from
	 * the cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 11:30:16
	 */
	int selectCount(GroupAuthRefKey record) throws DataAccessException;
	
	List<GroupAuthRefKey> selectByUserId(String userId) throws DataAccessException;
}