/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: GroupMapper.java
 * Creat Date: 2015-08-15 17:22:16
 */
package com.cloudwalk.ibis.repository.system;

import java.util.List;
import java.util.Map;

import org.springframework.cache.annotation.CachePut;
import org.springframework.dao.DataAccessException;

import com.cloudwalk.ibis.model.system.Group;
import com.google.code.ssm.api.InvalidateSingleCache;
import com.google.code.ssm.api.ParameterValueKeyProvider;
import com.google.code.ssm.api.ReadThroughMultiCache;
import com.google.code.ssm.api.ReadThroughSingleCache;
import com.google.code.ssm.api.UpdateSingleCache;

/**
 * Class Name: GroupMapper <br>
 * Description: This interface corresponds to the table - FND_GROUP <br>
 * Create Date: 2015-08-15 17:22:16 <br>
 */
public interface GroupMapper {
	int batchUpdate(List<Group> groups) throws DataAccessException;

	/**
	 * Method: deleteByPrimaryKey(...) <br/>
	 * Delete record from table - FND_GROUP<br/>
	 * Param: groupId (角色ID) , the paremeter can not empty. <br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP<br/>
	 * 2: GroupService call this method, then the realization method calls
	 * GroupMapper.xml to delete from database.<br/>
	 * 3: throws DataAccessException exception <br/>
	 * Remarks: If the method executed successfully, need to be removed Group
	 * object from memory cache Create Date: 2015-08-15 17:22:16
	 */
	@InvalidateSingleCache(namespace = "Group")
	int deleteByPrimaryKey(@ParameterValueKeyProvider String groupId) throws DataAccessException;

	/**
	 * Method: insertSelective(...) <br/>
	 * Insert a record to table - FND_GROUP<br/>
	 * Param: record, the paremeter can not empty, for details please to see
	 * Group.java model file.<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP<br/>
	 * 2: GroupService call this method, then the realization method calls
	 * GroupMapper.xml to add record into database.<br/>
	 * 3: throws DataAccessException exception <br/>
	 * Create Date: 2015-08-15 17:22:16
	 */
	@CachePut(value = "Group")
	int insertSelective(Group record) throws DataAccessException;

	int insertSelectiveBatch(List<Group> items) throws DataAccessException;

	/**
	 * Method: searchAll(...) <br/>
	 * Select some records from table - FND_GROUP <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP <br/>
	 * 2: GroupService call this method, then the realization method calls
	 * GroupMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Group correspondence from the
	 * cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 17:22:16
	 */
	@ReadThroughMultiCache(namespace = "Group", expiration = 30)
	List<Group> searchAll(Group record) throws DataAccessException;

	/**
	 * Method: searchAllByPage(...) <br/>
	 * Select some records from table by page- FND_GROUP <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP <br/>
	 * 2: GroupService call this method, then the realization method calls
	 * GroupMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Group correspondence from the
	 * cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 17:22:16
	 */
	@ReadThroughMultiCache(namespace = "Group", expiration = 30)
	List<Group> searchAllByPage(Map<String, Object> map) throws DataAccessException;

	/**
	 * Method: selectAll(...) <br/>
	 * Select some records from table - FND_GROUP <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP <br/>
	 * 2: GroupService call this method, then the realization method calls
	 * GroupMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Group correspondence from the
	 * cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 17:22:16
	 */
	@ReadThroughMultiCache(namespace = "Group", expiration = 30)
	List<Group> selectAll(Group record) throws DataAccessException;

	/**
	 * Method: selectAllByPage(...) <br/>
	 * Select some records from table by page- FND_GROUP <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP <br/>
	 * 2: GroupService call this method, then the realization method calls
	 * GroupMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Group correspondence from the
	 * cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 17:22:16
	 */
	@ReadThroughMultiCache(namespace = "Group", expiration = 30)
	List<Group> selectAllByPage(Map<String, Object> map) throws DataAccessException;

	/**
	 * Method: selectByPrimaryKey(...) <br/>
	 * Select a record from table - FND_GROUP <br/>
	 * Param: groupId (角色ID) , the paremeter can not empty. <br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP <br/>
	 * 2: GroupService call this method, then the realization method calls
	 * GroupMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughSingleCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Group correspondence from the
	 * cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 17:22:16
	 */
	@ReadThroughSingleCache(namespace = "Group", expiration = 30)
	Group selectByPrimaryKey(String groupId) throws DataAccessException;

	/**
	 * Method: selectCount(...) <br/>
	 * Select some records count from table - FND_GROUP <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records count<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP <br/>
	 * 2: GroupService call this method, then the realization method calls
	 * GroupMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Group correspondence from the
	 * cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 17:22:16
	 */
	int selectCount(Group record) throws DataAccessException;

	List<Group> selectGroupsByGroupNames(List<String> groupNames) throws DataAccessException;

	List<Group> selectGroupsByNames(Group g);
	
	List<Group> selectUserGroupsByUserIds(List<String> userIdList) throws DataAccessException;

	/**
	 * Method: updateByPrimaryKeySelective(...) <br/>
	 * Update record by primary key to table - FND_GROUP<br/>
	 * Param: record, the paremeter can not empty, for details please to see
	 * Group.java model file.<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_GROUP<br/>
	 * 2: GroupService call this method, then the realization method calls
	 * GroupMapper.xml to add record into database.<br/>
	 * 3: @UpdateSingleCache(namespace = "cache object name", expiration = cache
	 * expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Create Date: 2015-08-15 17:22:16
	 */
	@UpdateSingleCache(namespace = "Group", expiration = 30)
	int updateByPrimaryKeySelective(Group record) throws DataAccessException;


	
}