/**
 * Copyright @ 2015-2018 重庆中科云丛科技有限公司  All Rights Reserved.
 *
 * This file is automatically generated by MyBatis Generator, do not modify.
 * MyBatis Generator was modified by FUNDSTAR team, if you have any questions please contact with author.
 * Project Name: FundStar
 * File Name: OrganizationMapper.java
 * Creat Date: 2015-08-15 11:30:16
 */
package com.cloudwalk.ibis.repository.system;

import java.util.List;
import java.util.Map;

import org.springframework.cache.annotation.CachePut;
import org.springframework.dao.DataAccessException;

import com.cloudwalk.ibis.model.system.Organization;
import com.google.code.ssm.api.InvalidateSingleCache;
import com.google.code.ssm.api.ParameterValueKeyProvider;
import com.google.code.ssm.api.ReadThroughMultiCache;
import com.google.code.ssm.api.ReadThroughSingleCache;
import com.google.code.ssm.api.UpdateSingleCache;

/**
 * Class Name: OrganizationMapper <br>
 * Description: This interface corresponds to the table - FND_ORGANIZATION <br>
 * Create Date: 2015-08-15 11:30:16 <br>
 */
public interface OrganizationMapper {
	/**
	 * Method: deleteByPrimaryKey(...) <br/>
	 * Delete record from table - FND_ORGANIZATION<br/>
	 * Param: orgCode (机构代码) , the paremeter can not empty. <br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_ORGANIZATION<br/>
	 * 2: OrganizationService call this method, then the realization method
	 * calls OrganizationMapper.xml to delete from database.<br/>
	 * 3: throws DataAccessException exception <br/>
	 * Remarks: If the method executed successfully, need to be removed
	 * Organization object from memory cache Create Date: 2015-08-15 11:30:16
	 */
	@InvalidateSingleCache(namespace = "Organization")
	int deleteByPrimaryKey(@ParameterValueKeyProvider String orgCode) throws DataAccessException;

	/**
	 * Method: insertSelective(...) <br/>
	 * Insert a record to table - FND_ORGANIZATION<br/>
	 * Param: record, the paremeter can not empty, for details please to see
	 * Organization.java model file.<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_ORGANIZATION<br/>
	 * 2: OrganizationService call this method, then the realization method
	 * calls OrganizationMapper.xml to add record into database.<br/>
	 * 3: throws DataAccessException exception <br/>
	 * Create Date: 2015-08-15 11:30:16
	 */
	@CachePut(value = "Organization")
	int insertSelective(Organization record) throws DataAccessException;

	int isExistChildOrg(String orgCode) throws DataAccessException;

	int isExistsChildDept(String orgCode) throws DataAccessException;

	/**
	 * Method: searchAll(...) <br/>
	 * Select some records from table - FND_ORGANIZATION <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_ORGANIZATION <br/>
	 * 2: OrganizationService call this method, then the realization method
	 * calls OrganizationMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Organization correspondence from
	 * the cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 11:30:16
	 */
	@ReadThroughMultiCache(namespace = "Organization", expiration = 30)
	List<Organization> searchAll(Organization record) throws DataAccessException;
	
	@ReadThroughMultiCache(namespace = "Organization", expiration = 30)
	List<Organization> selectOrgsByEx(Organization record) throws DataAccessException;
	
	/**
	 * 根据当前机构编码获取所有父级法人机构编码
	 * @param record
	 * @return
	 * @throws DataAccessException
	 */
	List<String> selectParentCodes(String orgCode) throws DataAccessException;	

	/**
	 * Method: searchAllByPage(...) <br/>
	 * Select some records from table by page- FND_ORGANIZATION <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_ORGANIZATION <br/>
	 * 2: OrganizationService call this method, then the realization method
	 * calls OrganizationMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Organization correspondence from
	 * the cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 11:30:16
	 */
	// @ReadThroughMultiCache(namespace = "Organization", expiration = 30)
	List<Organization> searchAllByPage(Map<String, Object> map) throws DataAccessException;

	/**
	 * Method: selectAll(...) <br/>
	 * Select some records from table - FND_ORGANIZATION <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_ORGANIZATION <br/>
	 * 2: OrganizationService call this method, then the realization method
	 * calls OrganizationMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Organization correspondence from
	 * the cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 11:30:16
	 */
	@ReadThroughMultiCache(namespace = "Organization", expiration = 30)
	List<Organization> selectAll(Organization record) throws DataAccessException;

	/**
	 * Method: selectAllByPage(...) <br/>
	 * Select some records from table by page- FND_ORGANIZATION <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_ORGANIZATION <br/>
	 * 2: OrganizationService call this method, then the realization method
	 * calls OrganizationMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Organization correspondence from
	 * the cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 11:30:16
	 */
	@ReadThroughMultiCache(namespace = "Organization", expiration = 30)
	List<Organization> selectAllByPage(Map<String, Object> map) throws DataAccessException;

	/**
	 * Method: selectByPrimaryKey(...) <br/>
	 * Select a record from table - FND_ORGANIZATION <br/>
	 * Param: orgCode (机构代码) , the paremeter can not empty. <br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_ORGANIZATION <br/>
	 * 2: OrganizationService call this method, then the realization method
	 * calls OrganizationMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughSingleCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Organization correspondence from
	 * the cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 11:30:16
	 */
	@ReadThroughSingleCache(namespace = "Organization", expiration = 30)
	Organization selectByPrimaryKey(String orgCode) throws DataAccessException;
	
	/**
	 * 根据机构代码全路径查询
	 * @param orgCodePath
	 * @return
	 * @throws DataAccessException
	 */
	Organization selectByOrgCodePath(String orgCodePath) throws DataAccessException;	

	/**
	 * Method: selectCount(...) <br/>
	 * Select some records count from table - FND_ORGANIZATION <br/>
	 * Param: the record paremeter can be empty. If paremeter = null then return
	 * all records count<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_ORGANIZATION <br/>
	 * 2: OrganizationService call this method, then the realization method
	 * calls OrganizationMapper.xml to get record from database. <br/>
	 * 3: @ReadThroughMultiCache(namespace = "cache object name", expiration =
	 * cache expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Remarks: When the query set, first get Organization correspondence from
	 * the cache, such as the cache does not exist, <br/>
	 * then the query from the database, and stores the results into the cache.
	 * Create Date: 2015-08-15 11:30:16
	 */
	int selectCount(Organization record) throws DataAccessException;

	@ReadThroughMultiCache(namespace = "Organization", expiration = 30)
	List<Organization> selectOrganizationOrg(String orgCode) throws DataAccessException;

	/**
	 * Method: updateByPrimaryKeySelective(...) <br/>
	 * Update record by primary key to table - FND_ORGANIZATION<br/>
	 * Param: record, the paremeter can not empty, for details please to see
	 * Organization.java model file.<br/>
	 * Description: <br/>
	 * 1: This method corresponds to the database table FND_ORGANIZATION<br/>
	 * 2: OrganizationService call this method, then the realization method
	 * calls OrganizationMapper.xml to add record into database.<br/>
	 * 3: @UpdateSingleCache(namespace = "cache object name", expiration = cache
	 * expiration time(s) ) <br/>
	 * 4: throws DataAccessException exception <br/>
	 * Create Date: 2015-08-15 11:30:16
	 */
	@UpdateSingleCache(namespace = "Organization", expiration = 30)
	int updateByPrimaryKeySelective(Organization record) throws DataAccessException;

}